development:
  dialect: postgres
  datasource: postgres://xpose:asdfgklsdgkl@localhost:6869/xpose_db?sslmode=disable
  dir: migrations

production:
  dialect: postgres
  datasource: dbname=myapp sslmode=disable
  dir: migrations
  table: migrations
